### ISSUE TITLE
Footer: Page did not follow the SEO footer option #2 as stated in the project scope.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#1]
Reference:
https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking

Page should follow the SEO footer #2,
Web Design & Development by <a href=”http://www.titanweb.com.au” <?php if (!is_front_page()) { echo ‘rel=”nofollow”‘; }  ?> target=”_blank” title=”Titan Web”>Titan Web</a><img src=”<?php bloginfo(‘template_url’); ?>/images/titanweb-logo-dark.png” alt=”Titan Web”>

Screenshot(s):
![footer - 01](https://cloud.githubusercontent.com/assets/12888048/8514450/831535a6-23c2-11e5-9247-314374552774.jpg)

**Comment by arielcebudigital** [comment]
The scope was updated to #3 :-);

**Comment by romatitan** [comment]
The scope for SEO footer option # 2 was changed to # 3.
