### ISSUE TITLE
Homepage: The font used for the services item label was Roboto-slab and its font-size was set to 14px. It should be Roboto and 22px for font-size.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#11]
Screenshot(s):
![homepage - 06](https://cloud.githubusercontent.com/assets/12888048/8514896/2d581d28-23cb-11e5-9930-a2fc632af31c.jpg)

**Comment by arielcebudigital** [comment]
try to check the H3 itself, not the parent div

**Comment by romatitan** [comment]
Verified.
font-family: robotoregular;
font-size: 22px;
font-weight: normal
