### ISSUE TITLE
Homepage - devices: Navigation arrow (prev/next) overlapped to the services item title.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#111]
Affected device(s): S4, iPodtouch5 (portrait view)

![homepage - 25](https://cloud.githubusercontent.com/assets/12888048/9033747/b961f0f4-39fc-11e5-8d8b-a688e6b9d866.jpg)

**Comment by arielcebudigital** [comment]
There is no design for mobile and tablet,  so it should be overlap to fit in the mobile and tablet...

**Comment by romatitan** [comment]
According to Bernard, it should not overlap
