### ISSUE TITLE
Homepage - devices: There's no enough space between the navigation arrow(prev/next) and the services item title.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#112]
Affected device(s): 
S4, iPodtouch5 (portrait&landscape)
and iPad Air(portrait)

![2](https://cloud.githubusercontent.com/assets/12888048/8975059/e7b6abce-36ab-11e5-9e3b-8472918e20f1.png)

**Comment by arielcebudigital** [comment]
There is no design for mobile and tablet,  so it should be overlap to fit in the mobile and tablet...and the important part is the functionality.
