### ISSUE TITLE
Form and Checklists - Devices: Link - Devices: Item should be displayed in grid layout when the device is in landscape view/mode

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#116]
There still enough space to display the items in grid layout
![fc - 09](https://cloud.githubusercontent.com/assets/12888048/8975424/d18e520c-36b0-11e5-9f28-50e6f55026fd.jpg)

**Comment by arielcebudigital** [comment]
less than 768px it should be 1 column, for mobile.
