### ISSUE TITLE
Homepage: Flash of unstyled content 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#119]
![homepage - 28](https://cloud.githubusercontent.com/assets/12888048/8975586/64e3dd7c-36b3-11e5-9bb3-b713ae01fb5f.jpg)

**Comment by arielcebudigital** [comment]
try to refresh and wait.. it depend on the connection.

**Comment by romatitan** [comment]
According to Leoman, it is a bug.
If you have further question about this issue, you can communicate with Leoman.

Here's a reference link,
http://www.paulirish.com/2009/avoiding-the-fouc-v3/
http://modernizr.com/

**Comment by romatitan** [comment]
![homepage - 29](https://cloud.githubusercontent.com/assets/12888048/9078930/f855e81c-3b76-11e5-9b02-107efb7319f4.jpg)
![homepage - 30](https://cloud.githubusercontent.com/assets/12888048/9078929/f8528ed8-3b76-11e5-9cab-5abdc12151ac.jpg)
