### ISSUE TITLE
Header: The width and height of the "Our Portal" button differs from what the design has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#15]
Screenshot(s):
![header - 03](https://cloud.githubusercontent.com/assets/12888048/8515137/6f75c5ee-23cf-11e5-8dce-53ac6e1b2116.jpg)

**Comment by arielcebudigital** [comment]
This is not a bug, please kindly ask Bernard about it. We do our best to adjust everything..

**Comment by romatitan** [comment]
The width and height of "Our Portal" button was different from the design.
It should be W:147 H:53

![header - 12](https://cloud.githubusercontent.com/assets/12888048/8641858/17c15f1e-294e-11e5-82e5-f95742da5b16.jpg)

**Comment by arielcebudigital** [comment]
Hi, for Our Portal button the  exact size 145X52,
Select the Our Portal button and then hold ctr+T, you can see the exact size :-)
![our-portal-btn](https://cloud.githubusercontent.com/assets/11186408/8664703/61d96802-2a0d-11e5-85b6-9d6d95fed80b.png)
