### ISSUE TITLE
Header elements were not arranged properly.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#16]
Summary:
The arrangement of the icons, number and button differs from what the design has.
The social icon (google+) and the first letter of the header menu "Our Process" should be equally positioned - opposite to each other. 
Please check the screenshot for your reference.

Screenshot(s):
![header - 04](https://cloud.githubusercontent.com/assets/12888048/8515264/0a19d43a-23d2-11e5-9e60-a822c99eb1c7.jpg)

**Comment by arielcebudigital** [comment]
Again, this is not a bug, don't count every pixels to the header layout since everything will change specially when you adjust the screen.

**Comment by romatitan** [comment]
Verified fixed.
![header - 13](https://cloud.githubusercontent.com/assets/12888048/8641911/f7cc3480-294e-11e5-8e41-3c8130ea93d2.jpg)
