### ISSUE TITLE
Homepage: Header menu active state size is bigger compared to what the design has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#17]
Screenshot(s):

![header - 05](https://cloud.githubusercontent.com/assets/12888048/8515317/f3896a36-23d2-11e5-8d69-773087c958a0.jpg)

**Comment by arielcebudigital** [comment]
This is not a bug, please ask Bernard about this he knows a lot more about this stuff.

**Comment by romatitan** [comment]
I already ask Bernand.
Please check the padding, its bigger compared to what the design has.

**Comment by arielcebudigital** [comment]
checking the PSD, the padding should have padding-top:10 and padding-bottom:10, yet it's big so i adjust it to 8... i hope it is okay now.. not all the pixels is working fine in the PSD to the web.. 
![menu-padding](https://cloud.githubusercontent.com/assets/11186408/8664843/52997056-2a0f-11e5-9da2-6b19b4ed600d.png)
