### ISSUE TITLE
Header: The sub-menus background container is darker and has more rounder sides compared to what the design has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#18]
Screenshot(s):

![header - 06](https://cloud.githubusercontent.com/assets/12888048/8515364/af85d4d6-23d3-11e5-84d0-4b72e495fb80.jpg)

**Comment by arielcebudigital** [comment]
They have the same color::#c02c25, you can check it in the firebug

**Comment by romatitan** [comment]
Verified fixed
#c02c25
