### ISSUE TITLE
Banner: The font-weight for banner description was set to normal, even though the font was already robotolight still the output was different from the design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#21]
Screenshot(s):

![banner - 02](https://cloud.githubusercontent.com/assets/12888048/8515538/1a2a66fa-23d7-11e5-8f96-b6de365e3443.jpg)

**Comment by arielcebudigital** [comment]
This is not a bug, yes it's font-weight is normal...since the font-famliy is robotolight. by default.
