### ISSUE TITLE
Our Portal: Our portal [text acf] that link to external link was not implemented instead a pagelink was provided

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#24]
Screenshot(s):
![our portal - 01](https://cloud.githubusercontent.com/assets/12888048/8516099/4c598d62-23e2-11e5-9250-fe1589afe0be.jpg)

![our portal - 02](https://cloud.githubusercontent.com/assets/12888048/8516288/c57728d8-23e4-11e5-8643-eb5c8d6c7489.jpg)

**Comment by romatitan** [comment]
This should have an instruction like,
e.g http://example.com.au
for the client not to be mislead of what to input (url or domain)

![admin - 02](https://cloud.githubusercontent.com/assets/12888048/8642412/579ef31e-2956-11e5-86b7-8757c3543865.jpg)

**Comment by arielcebudigital** [comment]
Please try to clear cache before checking again :-)
![our-portal-admin](https://cloud.githubusercontent.com/assets/11186408/8664876/010ece4c-2a10-11e5-865d-f6844cbd6fb5.png)

**Comment by romatitan** [comment]
Our portal [text acf]  for external link was implemented.
Verified fixed.
