### ISSUE TITLE
Banner title was static. The changes did not apply.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#29]
Screenshot(s):
![banner - 05](https://cloud.githubusercontent.com/assets/12888048/8516671/d3580fa8-23e9-11e5-8f86-4fcb684f6cfa.jpg)

**Comment by arielcebudigital** [comment]
Please double check, it's working fine

**Comment by romatitan** [comment]
After changing the title of the banner. 
If a tab followed by another tab have the same title displayed, the next tab displayed a pop-up similar to the first.

![banner - 12](https://cloud.githubusercontent.com/assets/12888048/8643358/57350620-2965-11e5-9f37-35b54c25a8d1.jpg)

**Comment by arielcebudigital** [comment]
Hi Roma,

About the Banner Title it’s actually working fine, it just not display if the text is too long, try to change the Title not just adding it with long text ☺, that’s how the title should be implemented…

**Comment by arielcebudigital** [comment]
Again Banner title is not Static.

**Comment by romatitan** [comment]
Note: Created a separate ticket for this. Reference #93

 " From: romatitan [mailto:notifications@github.com]
Sent: Monday, July 13, 2015 1:45 PM
To: titan-cebu/Quest-Taxation
Cc: Ariel Gallamaso
Subject: Re: [Quest-Taxation] Banner title was static. The changes did not apply. (#29)


After changing the title of the banner.
If a tab followed by another tab have the same title displayed, the next tab displayed a pop-up similar to the first. "
