### ISSUE TITLE
In all page(s), unordered list content should display in 2 columns.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#35]
Screenshot(s):
![about us - 01](https://cloud.githubusercontent.com/assets/12888048/8517472/f00f97ce-23f3-11e5-8316-dc00ac37358a.jpg)

**Comment by arielcebudigital** [comment]
for 2 columns in unordered list content, it should become 1 column, :-)

**Comment by romatitan** [comment]
It should be displayed in 2 columns in desktop, 1 column in mobile.

**Comment by arielcebudigital** [comment]
Hi, Roma

Did you ask Bernard about this?, since before you came to titan we already discuss that it should be 1 columns as standard

**Comment by bernardtitan** [comment]
Hi Ariel,

Kindly link the standard which states that all lists should be displayed in one column.

**Comment by romatitan** [comment]
Verified fixed on desktop.

Note: Created a separate issue for : 
           Mobile: In all page(s), Content in an unordered list layout should be displayed in 1 column
          Reference #94
