### ISSUE TITLE
Our Services: The font used for "Read More" button label was roboto_slab and its font-weight was set to normal/regular.  It should be Roboto and light or 300 for font-weight.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#42]
Screenshot(s):
![services - 02](https://cloud.githubusercontent.com/assets/12888048/8518464/c786faaa-23fc-11e5-8ef1-e6227dbaeac3.jpg)

**Comment by arielcebudigital** [comment]
For Roboto Light, font-weight can be normal because it render the light weight by default :-)
