### ISSUE TITLE
Enhancement: Active / hover effect for breadcrumbs in services single page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#43]
Screenshot(s):
![services - 03](https://cloud.githubusercontent.com/assets/12888048/8518542/ab5cbd6e-23fd-11e5-9aae-0a454a500769.jpg)

**Comment by romatitan** [comment]
Please provide comment. Thanks.

**Comment by arielcebudigital** [comment]
For enhancement, please provide color, and please don't make this a bug since in PSD there is no active/hover state.

**Comment by romatitan** [comment]
Please follow the color scheme of the page.
