### ISSUE TITLE
Question: Does Our Process have single page(s)?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#47]
The Arrow, once click it will to Our Process single page,
 but the project scope stated to link it to Our Process page.

Screenshot(s):
![our process - 02](https://cloud.githubusercontent.com/assets/12888048/8519143/fdd9b434-2402-11e5-9f7b-7fb9af6e772b.jpg)

**Comment by arielcebudigital** [comment]
For this page, we don't have single page :-)
