### ISSUE TITLE
Clarification: What should be the field type for Checklist and Link Description?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#57]
Please update the project scope accordingly.
Screenshot(s):
![general - 01](https://cloud.githubusercontent.com/assets/12888048/8644747/49bf2eb2-2974-11e5-8353-42efa0d5fefa.jpg)

**Comment by romatitan** [comment]
Please provide comment. Thanks.

**Comment by arielcebudigital** [comment]
It should be textarea, I already update the admin.

**Comment by romatitan** [comment]
Verified fixed

![admin - 04](https://cloud.githubusercontent.com/assets/12888048/8713780/9f2358a6-2b9f-11e5-999f-6c6db4dad5fd.jpg)
![admin - 03](https://cloud.githubusercontent.com/assets/12888048/8713781/a0d197d0-2b9f-11e5-9e6a-7ba1fa57c9b2.jpg)
