### ISSUE TITLE
Links: The page did not follow a grid layout for its items. The link item description has a field type of wysiwyg, means it should accept any content layout.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#58]
Screenshot(s):
![links - 01](https://cloud.githubusercontent.com/assets/12888048/8537612/0e989dc6-2494-11e5-80b2-86530721bf7b.jpg)

**Comment by arielcebudigital** [comment]
We already update the project scope. It should be textarea :-)

**Comment by romatitan** [comment]
Verified link description field type as textarea.
