### ISSUE TITLE
Enhancement: Active/Hover state for image(s) in the gallery.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#65]

**Comment by romatitan** [comment]
Please provide comment. Thanks

**Comment by arielcebudigital** [comment]
For enhancement, please provide color, and please don't make this a bug since in PSD there is no active/hover state.

**Comment by romatitan** [comment]
Please follow the color scheme of the page.

**Comment by arielcebudigital** [comment]
Hi, for gallery image, i will not add hover state since there is no hover state in the PSD, we already ask bernard about this, my previsions comment was intended for pagination, :-)

**Comment by romatitan** [comment]
Enhancement not applied
