### ISSUE TITLE
Homepage: The "Read More/Less" button was smaller compared to what the design has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#7]
Screenshot(s):
![homepage - 02](https://cloud.githubusercontent.com/assets/12888048/8514677/7528d0ce-23c7-11e5-8d66-c7e8434b21a8.jpg)

**Comment by romatitan** [comment]
Read More/Less button has a longer width compared to the design.
It should have W: 124 H:52

![homepage - 17](https://cloud.githubusercontent.com/assets/12888048/8641493/d0124408-2948-11e5-9a7f-0227a8235a9e.jpg)

**Comment by arielcebudigital** [comment]
Hi, I send you the exact size for the button, 123 X 50, 
Select the button then press ctr+T, you will see the exact size. :-)
![button-size](https://cloud.githubusercontent.com/assets/11186408/8664422/b2569196-2a09-11e5-9736-f8a35765f076.png)
