### ISSUE TITLE
Banner tab needs to tap twice before the respective banner appears at the top

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#76]
Affected device(s): S4, iPodtouch5

Screenshot(s):
![banner - 09](https://cloud.githubusercontent.com/assets/12888048/8542872/6fbff5f4-24cb-11e5-87cc-e37fc8c870cf.jpg)

**Comment by arielcebudigital** [comment]
please check this link why single click not working, :-) 
https://discussions.apple.com/thread/3912739?tstart=0

**Comment by romatitan** [comment]
Verified fixed.
