### ISSUE TITLE
Homepage: Ideally the arrow, once tap, it should display its active state before linking to its respective page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#79]
Error occurs on devices.

Screenshot(s):
![homepage - 16](https://cloud.githubusercontent.com/assets/12888048/8543208/bf242fd2-24cd-11e5-9e0f-c1383f47a106.jpg)

**Comment by arielcebudigital** [comment]
This is not a bug, please check the difference for bug and enhancement.

**Comment by arielcebudigital** [comment]
desktop and tablet have different rendering. :-)

**Comment by romatitan** [comment]
Verified fixed.
