### ISSUE TITLE
Linkk: A blank nested repeater in a repeater with title occupied much space on the page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#86]
![link new](https://cloud.githubusercontent.com/assets/12888048/8646889/fcf58574-2985-11e5-914e-b921481b3958.jpg)

**Comment by arielcebudigital** [comment]
Hi Roma,

Yes it display another space because you add an empty row inside the repeater, and it does not make sense you add an empty row :-)

**Comment by bernardtitan** [comment]
Simply put, it can happen for placeholder purposes.

Beyond that, we need to trap all user input errors before they can begin. It's an empty row, it should be hidden.
