### ISSUE TITLE
News Single: The image should have rounded sides

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#88]
![news single new](https://cloud.githubusercontent.com/assets/12888048/8646931/59abd296-2986-11e5-83bb-3fe78c9b1f18.jpg)

**Comment by arielcebudigital** [comment]
Please clear cache before checking again :-)

**Comment by romatitan** [comment]
Verified fixed.

![news single - 02](https://cloud.githubusercontent.com/assets/12888048/8713473/77f35a14-2b9b-11e5-8b0c-98c49f850f25.jpg)
