### ISSUE TITLE
Services Single: Image should have rounded sides

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#89]
![services single new](https://cloud.githubusercontent.com/assets/12888048/8646937/64b2d162-2986-11e5-850e-29a699a005de.jpg)

**Comment by arielcebudigital** [comment]
Hi Roma, 

Please try to clear cache before checking again :-)

**Comment by romatitan** [comment]
Verified fixed.
![services single - 03](https://cloud.githubusercontent.com/assets/12888048/8713451/3eaed148-2b9b-11e5-9b83-4606730aaeb7.jpg)
