### ISSUE TITLE
Admin - Links Information [acf] : Field instructions should be provided.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#92]
Note: This was created as a separate issue from #24 

This should have an instruction like,
e.g http: // example.com.au
for the client not to be mislead of what to input (url or domain)

![admin - 02](https://cloud.githubusercontent.com/assets/12888048/8642412/579ef31e-2956-11e5-86b7-8757c3543865.jpg)

**Comment by arielcebudigital** [comment]
They can add domain or with url, since we already create a script that will filter the output.. to make it a correct url format.

**Comment by romatitan** [comment]
As per Leoman instruction, it should have field instructions.

**Comment by arielcebudigital** [comment]
Please try to clear cache before checking again, it's already fixed.

**Comment by romatitan** [comment]
![admin - 06](https://cloud.githubusercontent.com/assets/12888048/8974620/75667176-36a6-11e5-8f80-117d9bce3ecc.jpg)

**Comment by romatitan** [comment]
Please provide format for the link instruction.

**Comment by arielcebudigital** [comment]
For this page we don't need to put a format since it's a repeater not a text link :-), the format that you want should be display in Link Page (Format should be (http://example.com.au or example.com.au).)
