### ISSUE TITLE
Banner: After changing the title of the banner. If a tab followed by another tab have the same title displayed, the next tab displayed a pop-up similar to the first.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#93]
Note: This was created as a separate issue from #29 

Screenshot(s)
![banner - 12](https://cloud.githubusercontent.com/assets/12888048/8713905/af5bdde0-2ba1-11e5-8375-4abb90b591e8.jpg)

**Comment by romatitan** [comment]
New screenshot
![banner - 14](https://cloud.githubusercontent.com/assets/12888048/8715137/ed5d5a8e-2baf-11e5-8e09-109755225fac.jpg)

**Comment by arielcebudigital** [comment]
You put exactly same title, that is why it reflect that issue, Bernard suggested that it should be wont fix.. :-), next time try not to create the same title. :-)

**Comment by romatitan** [comment]
1.  With the second screenshot, it won't be fixed as they have totally same title.

2. But with my first screenshot, This is a bug.
I have different title per banner and the issue occurs.
If a tab followed by another tab have the same title displayed, the next tab displayed a pop-up similar to the first.

Test Title Banner 9
Test Title Banner 8
(both displayed as "Test Title", the error occurs)

Test Banner
Test Banner Title
(both displayed as "Test Banner", the error occurs)

And I verified this as fixed.
